### ISSUE TITLE
Proxy endpoint settings are inconsistent

### ISSUE THREAD

**Issue by ferozsalam** [cloudflare/odoh-server-go#6]
As part of 61171f56d06c07c49f3733770e8b3dcf490484af, the `proxyEndpoint` constant was removed in favour of using the `queryEndpoint` for both proxy and target requests, and the default for the `queryEndpoint` is set to `/dns-query`. However, [odoh-client-go](https://github.com/cloudflare/odoh-client-go) still attempts to hit `/proxy` (see [here](https://github.com/cloudflare/odoh-client-go/blob/master/commands/request.go#L54)), and this is hardcoded.

What is the desired behaviour here? Should the endpoint in `odoh-server-go` be changed back to `/proxy`, or should the `odoh-client-go` be updated to hit the `/dns-query` endpoint as well?

**Comment by tanyav2** [comment]
Fix for this should be merged very soon, thanks for flagging!
